### ISSUE TITLE
Problem with latest selenium-python lib.

### ISSUE THREAD

**Issue by Gateswong** [jbms/finance-dl#74]
I recently setup an environment which has "selenium  4.4.3" installed. It's been installed as a direct or indirect dependency of finance-dl. This version of selenium-python has the following change recently, which breaks all find element API calls:

https://github.com/baijum/selenium-python/commit/3b13c2f8f864c2b4a56fb5dddebab0cd86817ad6

Causes:

```
  File "somepath\.venv\lib\site-packages\finance_dl\scrape_lib.py", line 222, in wait_for_page_load
    old_page = self.driver.find_element_by_tag_name('html')
AttributeError: 'WebDriver' object has no attribute 'find_element_by_tag_name'
```

**Comment by Gateswong** [comment]
The lastest version of selenium that works with finance-dl is 4.2.0.

``` shell
pip install -Iv selenium==4.2.0
```

**Comment by Zburatorul** [comment]
Thanks for digging into this.
Are you willing to submit a PR with the right modifications to setup.py?

**Comment by chandler150** [comment]
Not a full solution, but it looks like since the Find_element_By... usage is depreciated, we are going to need to follow the guidelines here https://saucelabs.com/resources/articles/how-to-upgrade-to-selenium-4 to update
